name: ctrl
description: A package that allows you to control observables within scopes that are linked to the Widget Lifecycle.
version: 1.0.1
homepage: https://github.com/plooliveira/ctrl
repository: https://github.com/plooliveira/ctrl
issue_tracker: https://github.com/plooliveira/ctrl/issues
documentation: https://github.com/plooliveira/ctrl#readme

topics:
  - observer
  - observable
  - architecture
  - state-management
  - reactive

environment:
  sdk: ^3.10.0
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0

flutter:

  